changes for cicd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,7 +17,7 @@ jobs:
       # Checkout repository
       - uses: actions/checkout@v3
 
-      # Setup Java environment with Java 17
+      # Setup Java environment
       - uses: actions/setup-java@v3
         with:
           distribution: 'zulu'
@@ -37,30 +37,27 @@ jobs:
       # Install Android Command-Line Tools
       - name: Install Android Command-Line Tools
         run: |
-          mkdir -p "$ANDROID_HOME/cmdline-tools"
+          mkdir -p "$env:ANDROID_HOME\cmdline-tools\latest"
           curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-win-8512546_latest.zip
-          Expand-Archive -Path commandlinetools.zip -DestinationPath "$ANDROID_HOME/cmdline-tools"
-          
-          # Get the directory and rename it
-          $dir = Get-ChildItem -Path "$ANDROID_HOME/cmdline-tools" | Where-Object { $_.Name -ne "latest" } | Select-Object -First 1
-          if ($dir) {
-            Rename-Item -Path $dir.FullName -NewName "latest"
-          } else {
-            Write-Host "Directory for Android command line tools not found."
+          Expand-Archive -Path commandlinetools.zip -DestinationPath "$env:ANDROID_HOME\cmdline-tools\latest"
+
+      # Verify SDKManager Path
+      - name: Verify SDKManager Path
+        run: |
+          if (!(Test-Path "$env:ANDROID_HOME\cmdline-tools\latest\bin\sdkmanager.bat")) {
+            Write-Error "SDKManager not found at expected path: $env:ANDROID_HOME\cmdline-tools\latest\bin\sdkmanager.bat"
+            exit 1
           }
 
       # Install Android SDK Platforms and Tools
       - name: Install Android SDK Platforms and Tools
         run: |
-          $sdkmanager = "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager"
-          $arguments = "platforms;android-35", "build-tools;35.0.0"
-          & $sdkmanager $arguments
+          & "$env:ANDROID_HOME\cmdline-tools\latest\bin\sdkmanager.bat" "platforms;android-35" "build-tools;35.0.0"
 
       # Accept Android SDK Licenses
       - name: Accept Android SDK Licenses
-        shell: bash
         run: |
-          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
+          & "$env:ANDROID_HOME\cmdline-tools\latest\bin\sdkmanager.bat" --licenses | Out-Null
 
       # Clean Environment
       - name: Clean Environment
